### ISSUE TITLE
Support new 'datasources' structure in the yaml

### ISSUE THREAD

**Issue by lhein** [jboss-fuse/vscode-datavirt#111]
The yaml will contain a new structure for datasources. Each datasource will be listed inside 'datasources' element. 

```
datasources:
    - name: AccountsDB
      type: postgresql
      properties:
        - name: username
          value: user
        - name: password
          value: password
        - name: jdbc-url
          value: jdbc:postgresql://accounts/accounts
    - name: QuoteSvc
      type: rest
      properties:
        - name: endpoint
          value: https://finnhub.io/api/v1/
```
